/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

'use server'

import { b } from '../index';
import type { Check, Checked  } from "../types";
import type { Image, Audio, Pdf, Video } from "@boundaryml/baml";

import type {  BankTransaction,  CreditScoreAnalysis,  ExpenseBreakdown,  IncomeBreakdown } from "../types"

import type * as types from "../types"

/**
 * Streaming BAML server actions that return ReadableStreams.
 */

/**
 * Executes the streaming variant of the "AnalyzeBankStatement" BAML action.
 *
 * This action initiates a streaming response by calling the corresponding
 * BAML stream function. The returned stream yields incremental updates.
 *
 * @param { types.BankTransaction[] } transactions - Input parameter.
 *
 * @returns {ReadableStream<Uint8Array>} A stream that yields incremental updates from the action.
 */
export const AnalyzeBankStatement = async (
  transactions: types.BankTransaction[],
): Promise<ReadableStream<Uint8Array>> => {
  const stream = b.stream.AnalyzeBankStatement(
    transactions,
  );
  return Promise.resolve(stream.toStreamable());
};

/**
 * Executes the streaming variant of the "ExtractTransactions" BAML action.
 *
 * This action initiates a streaming response by calling the corresponding
 * BAML stream function. The returned stream yields incremental updates.
 *
 * @param { string } pdfText - Input parameter.
 *
 * @returns {ReadableStream<Uint8Array>} A stream that yields incremental updates from the action.
 */
export const ExtractTransactions = async (
  pdfText: string,
): Promise<ReadableStream<Uint8Array>> => {
  const stream = b.stream.ExtractTransactions(
    pdfText,
  );
  return Promise.resolve(stream.toStreamable());
};